### PR TITLE
Fix logging in fetchCheckForService

### LINKED ISSUE #28: error with container checks
Hi.

Trying sidecar another issue raised. Don't know if something I misunderstood, but it's not simple to search on the web for the type of error:

```
time="2018-09-09T19:11:22Z" level=warning msg="Adding check for service mysql:5.7@sha256:1d8f471c7e2929ee1e2bfbc1d16fc8afccd2e070afed24805487e726ce601a6d (id: 574d6ce4048a) failed. Got check type: , check args: ." 
```

### PR DESCRIPTION
**Pull request by mihaitodor**
Fixes #28. [CheckForService](https://github.com/Nitro/sidecar/blob/906372616ca1dac8143c9cc34f98a0814bcda10c/healthy/service_bridge.go#L130) will invoke `defaultCheckForService` when `check.Type` is not set via the `HealthCheck` label explicitly on the service.

### CODE REVIEW

File: healthy/service_bridge.go [hunk 1]
```diff
@@ -88,10 +88,7 @@ func (m *Monitor) fetchCheckForService(svc *service.Service, disco discovery.Dis
 	check := &Check{}
 	check.Type, check.Args = disco.HealthCheck(svc)
 	if check.Type == "" {
-		log.Warnf(
-			"Adding check for service %s (id: %s) failed. Got check type: %s, check args: %s.",
-			svc.Name, svc.ID, check.Type, check.Args,
-		)
+		log.Warnf("Got empty check type for service %s (id: %s)!", svc.Name, svc.ID)
```
Comment (relistan) [inline healthy/service_bridge.go]: It looks to me like this got a little orphaned in the refactor at some point. But the new message should still show the args in case some were returned.

Comment (mihaitodor) [reply healthy/service_bridge.go]: Indeed, the message is a bit redundant, since we'll get [this one](https://github.com/Nitro/sidecar/blob/a6345e5f19c7ebb187fb48f6f06f6f070e88a410/healthy/service_bridge.go#L133) anyway.

I got rid of it completely.
